# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'zeitwerk'

group :development, :test do
  gem 'pry'
  gem 'bigdecimal'
  gem 'rspec'
  gem 'rubocop'
  # Fixing warning: will no longer be part of the default gems starting from Ruby 3.5.0
  gem 'ostruct'
end
